# Generated by Django 4.2.28 on 2026-02-25 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('preparation_time', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(blank=True, max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('to_try', 'To try'), ('made_before', 'Made before')], default='to_try', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
